### ISSUE TITLE
dynamically decorate graphql aggregation schemas

### ISSUE THREAD

**Issue by sandford-ch** [embrio-tech/centrifuge-outflux#12]
As a pool operator, I want to specify that my aggregation logic in the pool config and use it to fetch my aggregated pod data, so that I can gain meaningful insights.

### Acceptance criteria
- [ ] Given aggregation logic stored in blender with a `name`, when outflux is started, then the aggregation schema is dynamically updated to include the `name` pipeline and point to the correct resolver.

**Comment by filo87** [comment]
#### Useful tools
https://the-guild.dev/graphql/envelop/plugins/use-schema

Pool Metadata: https://altair.mypinata.cloud/ipfs/QmYjGoC7rvDXaJzeaC5U3JA68EZQE9hwvU6GQukJ3F5CbE

**Comment by filo87** [comment]
Pool Metadata: https://altair.mypinata.cloud/ipfs/QmYjGoC7rvDXaJzeaC5U3JA68EZQE9hwvU6GQukJ3F5CbE
