### ISSUE TITLE
query public data for multiple pools from single instances

### ISSUE THREAD

**Issue by filo87** [embrio-tech/centrifuge-outflux#21]
### User story

> **As** a analytics user
**I want** to query public aggregations for different pools without authentication
**So that** i can gain meaningful insights on the ecosystem

### Acceptance criteria

- [x] ~~Each pool requires a dedicated and unauthenticated public graphql endpoint where all public resolvers are mapped: `/pools/{poolId}/graphql/public`~~
- [x] A pool's graph contains public and private fields
- [x] all graph fields are private per default and require authentication
- [x] Public fields (i.e. `aggregations`), can be queried without authentication

**Comment by tibohei** [comment]
- what are the public resolvers?
- are just some aggregations public or are the other parts of the graph which are public?
