### ISSUE TITLE
implement changes to data model

### ISSUE THREAD

**Issue by sandford-ch** [embrio-tech/centrifuge-outflux#6]
Related to embrio-tech/centrifuge-influx#8

### Acceptance Criteria

- [x] update graphql types and db models according to embrio-tech/centrifuge-influx#8
- [x] custom scalar for supported entity types
- [x] support specification of `Entity.type` as query parameter
- [x] fix resolve correct `Frame` for each `Source`

**Comment by tibohei** [comment]
we could not test this with actual data due breaking changes on the chain and subquery subquery and chain.
