### ISSUE TITLE
authenticate with JW3T

### ISSUE THREAD

**Issue by sandford-ch** [embrio-tech/centrifuge-outflux#7]
### User Story

> **As** pool owner or loan taker  
**I want** that only authenticated users can access protected data  
**so that** confidentiality is guaranteed.

### Acceptance Criteria

- [x] read jw3t from request header (Bearer Token)
- [x] verify jw3t using [JW3T Lib](https://github.com/hamidra/jw3t)
- [x] decorate request object with jw3t payload (i.e. user info)
- [x] Protect entire graphql endpoint with token
- [x] ~~try to make graphiQL playground available without token (optional spike, within story point budget)~~ It's not recommended to run graphiQL for production environments ([more about it](https://graphql.org/learn/serving-over-http/#graphiql)). Thus, we do not serve it when auth is required.

### For follow-up tickets
- [x] Protect single resolvers (fields) with token
- [x] or explicitly unprotect some resolvers (fields)

➡️ see [comment](https://github.com/embrio-tech/centrifuge-outflux/issues/7#issuecomment-1484806040)

**Comment by filo87** [comment]
JW3T Lib: https://github.com/hamidra/jw3t

**Comment by tibohei** [comment]
We can maybe use the [`useGenericAuth`](https://the-guild.dev/graphql/envelop/plugins/use-generic-auth) plugin for fine-granular access control
